"""added onupgdate cascade

Revision ID: 0dbc543edb1d
Revises: 61eda6f78af9
Create Date: 2022-01-09 21:15:23.369600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0dbc543edb1d'
down_revision = '61eda6f78af9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('employee_ibfk_1', 'employee', type_='foreignkey')
    op.create_foreign_key(None, 'employee', 'department', ['dept_name'], ['name'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employee', type_='foreignkey')
    op.create_foreign_key('employee_ibfk_1', 'employee', 'department', ['dept_name'], ['name'], ondelete='CASCADE')
    # ### end Alembic commands ###
