"""first migration

Revision ID: 61eda6f78af9
Revises: 
Create Date: 2022-01-08 22:25:06.912220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61eda6f78af9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_department_id'), 'department', ['id'], unique=False)
    op.create_table('employee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('surname', sa.String(length=20), nullable=False),
    sa.Column('date_of_bidth', sa.Date(), nullable=True),
    sa.Column('salary', sa.Integer(), nullable=False),
    sa.Column('dept_name', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['dept_name'], ['department.name'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_date_of_bidth'), 'employee', ['date_of_bidth'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employee_date_of_bidth'), table_name='employee')
    op.drop_table('employee')
    op.drop_index(op.f('ix_department_id'), table_name='department')
    op.drop_table('department')
    # ### end Alembic commands ###
