"""added ondelete cascade to parent_employee relation

Revision ID: 66b6cfe68a8a
Revises: f5a488772846
Create Date: 2021-12-16 20:33:06.432414

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '66b6cfe68a8a'
down_revision = 'f5a488772846'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employee', 'name',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
    op.alter_column('employee', 'surname',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
    op.alter_column('employee', 'dept_name',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
    op.drop_constraint('employee_ibfk_1', 'employee', type_='foreignkey')
    op.create_foreign_key(None, 'employee', 'department', ['dept_name'], ['name'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employee', type_='foreignkey')
    op.create_foreign_key('employee_ibfk_1', 'employee', 'department', ['dept_name'], ['name'])
    op.alter_column('employee', 'dept_name',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
    op.alter_column('employee', 'surname',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
    op.alter_column('employee', 'name',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
    # ### end Alembic commands ###
