"""added employee model

Revision ID: 85c54b0ab9fc
Revises: e22e834de1f9
Create Date: 2021-12-11 18:34:15.153446

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '85c54b0ab9fc'
down_revision = 'e22e834de1f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('surname', sa.String(length=20), nullable=True),
    sa.Column('date_of_bidth', sa.Date(), nullable=True),
    sa.Column('salary', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_date_of_bidth'), 'employee', ['date_of_bidth'], unique=False)
    op.alter_column('department', 'name',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
    op.create_index(op.f('ix_department_name'), 'department', ['name'], unique=False)
    op.drop_column('department', 'descr')
    op.drop_column('department', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('department', sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False))
    op.add_column('department', sa.Column('descr', mysql.VARCHAR(length=50), nullable=True))
    op.drop_index(op.f('ix_department_name'), table_name='department')
    op.alter_column('department', 'name',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
    op.drop_index(op.f('ix_employee_date_of_bidth'), table_name='employee')
    op.drop_table('employee')
    # ### end Alembic commands ###
