"""empty message

Revision ID: e22e834de1f9
Revises: 39dd740cd159
Create Date: 2021-12-10 22:33:05.435947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e22e834de1f9'
down_revision = '39dd740cd159'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('department', sa.Column('descr', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('department', 'descr')
    # ### end Alembic commands ###
