#the default linux distribution is ok
#dist: xenial

branches:
  except:
    - main

language: python
python:
  - 3.8

#env:

install:
  - pip install -r requirements.txt
script:
  - pylint $(git ls-files '*.py') | cat > lint_report.html


#after_success:
#  - merge with main branch