#the default linux distribution is ok
#dist: xenial

branches:
  except:
    - main

language: python
python:
  - 3.8

#env:

install:
  - pip install -r requirements.txt

script:
  - python test/lint.py 10

notifications:
  email:
    on_success: never
    on_failure: always


#after_success:
#  - merge with main branch