#the default linux distribution is ok
#dist: xenial

language: python
python:
  - 3.8

install:
  - pip install -r requirements.txt

script:
  - pylint app
  - coverage run -m unittest discover
  - coverage report

after_success:
  - coveralls
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then bash auto-merge.sh; fi'

notifications:
  email:
    on_success: never
    on_failure: always
