#the default linux distribution is ok
#dist: xenial

branches:
  except:
    - main

language: python
python:
  - 3.8

install:
  - pip install -r requirements.txt

#script:
#  - python test/lint.py

after_success:
  - git log --oneline
  - git remote add travis https://${GIT_TOKEN}@github.com/TonySol/fin.git
  - git branch travis_test
  - git branch
  - git push –u tavis travis_test
#  - git checkout main
#  - git merge --no-ff dev
#  - git push travis main

notifications:
  email:
    on_success: never
    on_failure: always


#after_success:
#  - merge with main branch


