"""added one-to-mane relationship

Revision ID: f5a488772846
Revises: 85c54b0ab9fc
Create Date: 2021-12-11 18:38:00.244736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5a488772846'
down_revision = '85c54b0ab9fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_department_name', table_name='department')
    op.create_index(op.f('ix_department_name'), 'department', ['name'], unique=True)
    op.add_column('employee', sa.Column('dept_name', sa.String(length=20), nullable=False))
    op.create_foreign_key(None, 'employee', 'department', ['dept_name'], ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employee', type_='foreignkey')
    op.drop_column('employee', 'dept_name')
    op.drop_index(op.f('ix_department_name'), table_name='department')
    op.create_index('ix_department_name', 'department', ['name'], unique=False)
    # ### end Alembic commands ###
